from fastapi import APIRouter, HTTPException, status
from fastapi.responses import FileResponse, PlainTextResponse
from pathlib import Path
from app.models.stream import StreamStatus
from app.services.stream_manager import stream_manager
from app.config import settings

router = APIRouter(prefix="/stream", tags=["streaming"])


@router.get("/{channel_id}/master.m3u8")
async def get_master_playlist(channel_id: str):
    """
    Get HLS master playlist for a channel.
    This will start the stream if not already running.
    """
    # Start stream if not active
    success = await stream_manager.start_stream(channel_id)

    if not success:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Channel {channel_id} not found or cannot start stream"
        )

    # For single-bitrate streams, we just redirect to the stream playlist
    # In a multi-bitrate setup, this would list multiple quality levels
    stream_url = f"stream.m3u8"

    # Return simple master playlist
    content = f"#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-STREAM-INF:BANDWIDTH=3000000\n{stream_url}\n"

    return PlainTextResponse(
        content=content,
        media_type="application/vnd.apple.mpegurl"
    )


@router.get("/{channel_id}/stream.m3u8")
async def get_stream_playlist(channel_id: str):
    """
    Get HLS media playlist (generated by FFmpeg).
    """
    stream_manager.track_request(channel_id)

    playlist_path = settings.streams_dir / channel_id / "stream.m3u8"

    if not playlist_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Stream playlist not found"
        )

    return FileResponse(
        playlist_path,
        media_type="application/vnd.apple.mpegurl"
    )


@router.get("/{channel_id}/{segment_name}")
async def get_segment(channel_id: str, segment_name: str):
    """
    Get HLS segment file.
    """
    # Validate segment name to prevent directory traversal
    if ".." in segment_name or "/" in segment_name or "\\" in segment_name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid segment name"
        )

    stream_manager.track_request(channel_id)

    segment_path = settings.streams_dir / channel_id / segment_name

    if not segment_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Segment not found"
        )

    return FileResponse(
        segment_path,
        media_type="video/MP2T"
    )


@router.get("/{channel_id}/status", response_model=StreamStatus)
async def get_stream_status(channel_id: str):
    """Get stream status."""
    return stream_manager.get_stream_status(channel_id)


@router.post("/{channel_id}/restart")
async def restart_stream(channel_id: str):
    """Restart a stream."""
    await stream_manager.stop_stream(channel_id)
    success = await stream_manager.start_stream(channel_id)

    if not success:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to restart stream"
        )

    return {"status": "restarted"}
